name: 'Build'

on: push

jobs:
  build:
    name: 'Construir'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Configurar JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Verificar submodulos'
        uses: textbook/git-checkout-submodule-action@master
      - name: 'Instalar dependencias de 32 bits'
        run: sudo apt update && sudo apt-get install -y libc6-i386 lib32z1 lib32stdc++6
      - name: 'Construir extension'
        run: ant extensions -Dproguard=0 -Xdiags:verbose
      - name: 'Publicar a Artefactos'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: uy.abstudios.cinelartv.mediaclient.CastExtension.aix
          path: out/uy.abstudios.cinelartv.mediaclient.CastExtension.aix
     
