name: 'Build'

on: push

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Checkout submodules'
        uses: textbook/git-checkout-submodule-action@master
      - name: 'Install 32-bit dependencies'
        run: sudo apt-get install -y libc6-i386 lib32z1 lib32stdc++6  --fix-missing
      - name: 'Construir extension'
        run: ant extensions -Dproguard=1
      - name: 'Upload Companion to Artifacts'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: uy.abstudios.cinelartv.mediaclient.aix
          path: out/uy.abstudios.cinelartv.mediaclient.aix
     
